package localhost._8010;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-08-26T07:54:45.720Z
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://localhost:8010", name = "helloWSDL")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWSDL {

    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://localhost:8010", className = "localhost._8010.SayHelloResponse")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://localhost:8010", className = "localhost._8010.SayHello")
    @WebResult(name = "out", targetNamespace = "")
    @WebMethod(action = "http://localhost:8010/NewOperation")
    public java.lang.String sayHello(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
