
/*
 * 
 */

package localhost._8010;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-08-26T07:54:45.792Z
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "helloWSDL", 
                  wsdlLocation = "file:src/main/resources/helloWSDL.wsdl",
                  targetNamespace = "http://localhost:8010") 
public class HelloWSDL_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8010", "helloWSDL");
    public final static QName HelloWSDLSOAP = new QName("http://localhost:8010", "helloWSDLSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/helloWSDL.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/helloWSDL.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloWSDL_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWSDL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSDL_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWSDL_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWSDL_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWSDL_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWSDL
     */
    @WebEndpoint(name = "helloWSDLSOAP")
    public HelloWSDL getHelloWSDLSOAP() {
        return super.getPort(HelloWSDLSOAP, HelloWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWSDL
     */
    @WebEndpoint(name = "helloWSDLSOAP")
    public HelloWSDL getHelloWSDLSOAP(WebServiceFeature... features) {
        return super.getPort(HelloWSDLSOAP, HelloWSDL.class, features);
    }

}
