
package localhost._8010;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-08-26T07:54:45.779Z
 * Generated source version: 2.3.3
 * 
 */
 
public class HelloWSDL_HelloWSDLSOAP_Server{

    protected HelloWSDL_HelloWSDLSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWSDLImpl();
        String address = "http://localhost:8010/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new HelloWSDL_HelloWSDLSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
